// src/app/services/orientation.service.ts
import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class DealsOffersService {
    deals = [
        {
            id: 1,
            name: '777 Café AL WASL CHEVAL MAISON HOTEL',
            discount: '20%',
            open: '8 AM - 10 PM',
            budget: 'Low Budget (20-30AED)',
            contact: '+971627412824',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-seven.png',
        },
        {
            id: 2,
            name: 'Ten 11',
            discount: '20%',
            open: '7 AM - 10 PM',
            budget: 'Low Budget (20-30AED)',
            contact: '+971526032182',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-ten11.png',
        },
        {
            id: 3,
            name: 'The Daily',
            discount: '20%',
            open: '6:30 AM - 11:30 PM',
            budget: 'High Budget (>50 AED)',
            contact: '+971529673621',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-the-daily.png',
        },
        {
            id: 4,
            name: 'YAMANOTE',
            discount: '20%',
            open: '8 AM - 8 PM',
            budget: 'Medium Budget (30-50 AED)',
            contact: '+971559927659',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-yamanote-collective.png',
        },
        {
            id: 5,
            name: 'PizzaExpress',
            discount: '15%',
            open: '10 AM - 07 PM',
            budget: 'Medium Budget (30-50 AED)',
            contact: '+97143945616',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-pizza-express.png',
        },
        {
            id: 6,
            name: 'PDL',
            discount: '20%',
            open: '7 AM - 4 PM',
            budget: 'Low Budget (20-30AED)',
            contact: '+971567713090',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-pdl.png',
        },
        {
            id: 7,
            name: 'TALHAN',
            discount: '20%',
            open: '11 AM - 11 PM',
            budget: 'Medium Budget (30-50 AED)',
            contact: '+971527713922',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-talhan.png',
        },
        {
            id: 8,
            name: 'CHOY',
            discount: '20%',
            open: '9 AM - 9 PM',
            budget: 'Medium Budget (30-50 AED)',
            contact: '+97152074667',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-chay.png',
        },
        {
            id: 9,
            name: 'PXB',
            discount: '20%',
            open: '8 AM - 6 PM',
            budget: 'Medium Budget (30-50 AED)',
            contact: '+971564309815',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-pxb.png',
        },
        {
            id: 10,
            name: 'SOUL SOUP',
            discount: 'N/A',
            open: '9 AM - 6 PM',
            budget: 'Low Budget (20-30AED)',
            contact: null,
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-soule-soups.png',
        },
        {
            id: 11,
            name: 'AL BAIK',
            discount: 'N/A',
            open: '10 AM - 11:30 PM',
            budget: 'Low Budget (20-30AED)',
            contact: '+97156547445',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-al-baik.png',
        },
        {
            id: 12,
            name: 'Right Bite',
            discount: '20%',
            open: null,
            budget: null,
            contact: null,
            promoCode: 'nestlexhealth',
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-right-bite.png',
        },
        {
            id: 13,
            name: 'kcal',
            discount: '20%',
            open: null,
            budget: null,
            contact: '+971529879729',
            promoCode: null,
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-kcal.png',
        },
        {
            id: 14,
            name: 'Vmeals',
            discount: '25%',
            open: null,
            budget: null,
            contact: '0503009794',
            promoCode: 'NESTLE25',
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-meals.png',
        },
        {
            id: 15,
            name: 'WYLD',
            discount: '30%',
            open: null,
            budget: null,
            contact: '+971581306832',
            promoCode: 'NESTLE25',
            image: 'https://nestle-public-access-uae.s3.me-central-1.amazonaws.com/deals/deals-wyld.png',
        },
    ];

    getDeals() {
        return this.deals;
    }
    GetDealById(id: number) {
        console.log('hiiii' + this.deals.find((s) => s.id === id));
        return this.deals.find((s) => s.id === id);
    }
}
